import * as THREE from "three";
import { OrbitControls } from "three/examples/jsm/controls/OrbitControls.js";
import data from "./baul-data.json";
import { catalog, defaultClient } from "./catalog.js";
import "./styles.css";
import { responsiveCamera } from "./responsive-camera.js";

const route=new URLSearchParams(location.search),hasDirectPiece=route.has("pieza")||route.has("p");
function showCatalog(){
 const clientList=document.getElementById("clientList"),furnitureList=document.getElementById("furnitureList"),clientStep=document.getElementById("clientStep"),furnitureStep=document.getElementById("furnitureStep");let activeClient=route.get("cliente")||null;
 const clients=()=>clientList.replaceChildren(...Object.entries(catalog).map(([slug,client])=>{const b=document.createElement("button");b.className="catalog-card";b.type="button";b.innerHTML=`<span class="card-label">CLIENTE</span><strong>${client.name}</strong><small>${client.client} · ${client.description}</small><span class="card-action">Ver muebles →</span>`;b.onclick=()=>{activeClient=slug;furniture();};return b;}));
 const furniture=()=>{const client=catalog[activeClient];if(!client)return;clientStep.hidden=true;furnitureStep.hidden=false;document.getElementById("selectedClientName").textContent=`${client.name} · ${client.client}`;furnitureList.replaceChildren(...Object.entries(client.furniture).map(([slug,item])=>{const b=document.createElement("button");b.className="catalog-card furniture-card";b.type="button";b.innerHTML=`<span class="card-label">MUEBLE</span><strong>${item.name}</strong><small>${item.description}</small><span class="card-action">Abrir visor 3D →</span>`;b.onclick=()=>location.href=`?cliente=${activeClient}&mueble=${slug}`;return b;}));};
 document.getElementById("backToClients").onclick=()=>{activeClient=null;furnitureStep.hidden=true;clientStep.hidden=false;history.replaceState({},"",location.pathname);};clients();if(activeClient&&catalog[activeClient])furniture();
}
function startViewer(){
 document.getElementById("catalogApp").hidden=true;document.getElementById("viewerApp").hidden=false;document.getElementById("clientName").textContent="PICKY KIDS · GUÍA DE ARMADO 3D";document.getElementById("productName").textContent="Baúl Emi";document.getElementById("sceneName").textContent="Baúl";document.getElementById("homeButton").onclick=()=>location.href=location.pathname;
 const pieces={tapa:"Tapa",frente:"Frente",fondo:"Fondo",lateral:"Laterales",base:"Base"},select=document.getElementById("pieceSelect");select.replaceChildren(...Object.entries(pieces).map(([v,l])=>{const o=document.createElement("option");o.value=v;o.textContent=l;return o;}));
 const U=.01,T=data.thickness,canvas=document.getElementById("viewer"),renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.shadowMap.enabled=true;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;
 const scene=new THREE.Scene();scene.fog=new THREE.Fog(0xe9eee9,110,170);const camera=new THREE.PerspectiveCamera(31,1,.05,180),controls=new OrbitControls(camera,canvas);controls.enableDamping=true;controls.dampingFactor=.07;controls.maxPolarAngle=Math.PI*.6;const framing=responsiveCamera(camera,controls,canvas,1.3);scene.add(new THREE.HemisphereLight(0xffffff,0x68746c,2.2));const sun=new THREE.DirectionalLight(0xffffff,3.1);sun.position.set(9,13,10);sun.castShadow=true;scene.add(sun);
 const wood=new THREE.MeshStandardMaterial({color:0x9aae72,roughness:.73}),selected=new THREE.MeshStandardMaterial({color:0xe3262e,roughness:.42,emissive:0x5a0000,emissiveIntensity:.22}),edgeMat=new THREE.LineBasicMaterial({color:0x263b22,transparent:true,opacity:.58}),pointMat=new THREE.MeshStandardMaterial({color:0x177da3,roughness:.4,emissive:0x063848,emissiveIntensity:.18});
 const root=new THREE.Group();root.scale.setScalar(U);scene.add(root);const parts=[],markers=[];
 function transformedProfile(key,mode){const p=data.profiles[key],points=p.outline.map(([x,y])=>mode==='swap'?[y,x]:[x,y]);return {points,width:mode==='swap'?p.height:p.width,height:mode==='swap'?p.width:p.height};}
 function geometry(key,mode='plain'){const p=transformedProfile(key,mode),s=new THREE.Shape();p.points.forEach(([x,y],i)=>i?s.lineTo(x,y):s.moveTo(x,y));s.closePath();const g=new THREE.ExtrudeGeometry(s,{depth:T,bevelEnabled:true,bevelSegments:2,bevelSize:.75,bevelThickness:.75,curveSegments:6});g.computeBoundingBox();const b=g.boundingBox;g.translate(-(b.min.x+b.max.x)/2,-(b.min.y+b.max.y)/2,-T/2);g.computeVertexNormals();return g;}
 function addPart(type,key,pos,rot,explode,mode='plain'){const group=new THREE.Group(),g=geometry(key,mode),mesh=new THREE.Mesh(g,wood);mesh.castShadow=true;mesh.receiveShadow=true;mesh.userData.partType=type;group.add(mesh);group.add(new THREE.LineSegments(new THREE.EdgesGeometry(g,24),edgeMat));group.position.set(...pos);group.rotation.set(...rot);group.userData={base:new THREE.Vector3(...pos),explode:new THREE.Vector3(...explode),partType:type};parts.push({group,mesh,type});root.add(group);return group;}
 function dot(parent,x,y,z,d=8,axis='z'){const r=Math.max(d/2,3),m=new THREE.Mesh(new THREE.CylinderGeometry(r,r,1.6,18),pointMat);m.position.set(x,y,z);if(axis==='z')m.rotation.x=Math.PI/2;if(axis==='x')m.rotation.z=Math.PI/2;m.visible=false;m.userData.partType=parent.userData.partType;parent.add(m);markers.push(m);}
 function addMachining(group,key,program,mode='plain',faceSign=1,dedupe=false){const prof=transformedProfile(key,mode),p=data.programs[program],seen=new Set();for(const op of p.operations){let x=op.x,y=op.y;if(key.startsWith('lateral'))[x,y]=[op.y,p.length-op.x];let nx=0,ny=0,edge=false;if(op.type==='Horizontal Hole'){if(Math.abs(x)<.3){nx=-1;edge=true;}else if(Math.abs(x-prof.width)<.3){nx=1;edge=true;}else if(Math.abs(y)<.3){ny=-1;edge=true;}else if(Math.abs(y-prof.height)<.3){ny=1;edge=true;}else continue;}const k=`${x.toFixed(1)}:${y.toFixed(1)}:${edge?`${nx},${ny}`:faceSign}`;if(dedupe&&seen.has(k))continue;seen.add(k);const px=x-prof.width/2,py=y-prof.height/2;if(edge)dot(group,px+nx*.8,py+ny*.8,0,op.diameter,Math.abs(nx)>.5?'x':'y');else dot(group,px,py,faceSign*(T/2+.8),op.diameter,'z');}}
 const a=data.assembly,frontY=a.sideHeight-a.panelHeight/2;
 const front=addPart('frente','frente',[0,frontY,a.sideDepth/2],[0,0,0],[0,0,150],'swap');addMachining(front,'frente','MA000904000503180101.xml','swap',-1);
 const back=addPart('fondo','fondo',[0,frontY,-a.sideDepth/2],[0,Math.PI,0],[0,0,-150],'swap');addMachining(back,'fondo','MA000904000502180101.xml','swap',1);
 const sideX=a.frontWidth/2-T/2,left=addPart('lateral','lateral-a',[-sideX,a.sideHeight/2,0],[0,-Math.PI/2,0],[-170,0,0]),right=addPart('lateral','lateral-b',[sideX,a.sideHeight/2,0],[0,Math.PI/2,0],[170,0,0]);addMachining(left,'lateral-a','MA000904000504180101.xml','plain',1,true);addMachining(right,'lateral-b','MA000904000504180101.xml','plain',1,true);
 const base=addPart('base','base',[0,62,0],[-Math.PI/2,0,0],[0,-30,260]);addMachining(base,'base','MA000904000501180101.xml');
 const lid=addPart('tapa','tapa',[0,a.sideHeight,-a.sideDepth/2],[-.18,0,0],[0,135,-35],'swap');addMachining(lid,'tapa','MA000904000505180101.xml','swap',-1);for(const child of lid.children)child.position.y+=a.lidDepth/2;
 const ground=new THREE.Mesh(new THREE.PlaneGeometry(20,16),new THREE.MeshStandardMaterial({color:0xdfe5df,roughness:1}));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;scene.add(ground);
 let active=route.get('pieza')||'tapa',amount=0;if(!pieces[active])active='tapa';select.value=active;function refresh(){for(const i of parts)i.mesh.material=i.type===active?selected:wood;for(const p of markers)p.visible=amount>.03&&(p.userData.partType===active||amount>.7);}function explode(v){amount=v;for(const {group} of parts)group.position.copy(group.userData.base).addScaledVector(group.userData.explode,v);refresh();}
 select.onchange=()=>{active=select.value;refresh();const u=new URL(location.href);u.searchParams.set('cliente','picky-kids');u.searchParams.set('mueble','baul-emi');u.searchParams.set('pieza',active);history.replaceState({},'',u);};const slider=document.getElementById('explode'),button=document.getElementById('explodeButton');slider.value='0';slider.oninput=()=>{const v=Number(slider.value);explode(v/100);button.textContent=v===100?'Ver armado completo':'Ver despiece completo';};button.onclick=()=>{slider.value=slider.value==='100'?'0':'100';explode(Number(slider.value)/100);button.textContent=slider.value==='100'?'Ver armado completo':'Ver despiece completo';};
 camera.position.set(13,9,15);controls.target.set(0,1.7,0);controls.minDistance=5;controls.maxDistance=90;refresh();function resize(){renderer.setSize(canvas.clientWidth,canvas.clientHeight,false);framing.resize();}new ResizeObserver(resize).observe(canvas);resize();function animate(){requestAnimationFrame(animate);controls.update();renderer.render(scene,camera);}animate();document.getElementById('loading').classList.add('ready');
}
if(route.has('mueble')||hasDirectPiece)startViewer();else showCatalog();
