import * as THREE from 'three';
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js';
import { catalog, defaultClient, defaultFurniture, getProduct } from './catalog.js';
import './styles.css';
const route=new URLSearchParams(location.search), product=getProduct(route.get('cliente')||defaultClient,route.get('mueble')||defaultFurniture); const direct=route.has('mueble')||route.has('pieza')||route.has('p');
function catalogView(){document.getElementById('clientList').innerHTML='';document.getElementById('furnitureList').innerHTML=''; for(const [slug,c] of Object.entries(catalog)){const b=document.createElement('button');b.className='catalog-card';b.innerHTML=`<span class="card-label">CLIENTE</span><strong>${c.name}</strong><small>${c.client} · ${c.description}</small><span class="card-action">Ver muebles →</span>`;b.onclick=()=>{document.getElementById('clientStep').hidden=true;document.getElementById('furnitureStep').hidden=false;document.getElementById('selectedClientName').textContent=`${c.name} · ${c.client}`;for(const [m,f] of Object.entries(c.furniture)){const q=document.createElement('button');q.className='catalog-card';q.innerHTML=`<span class="card-label">MUEBLE</span><strong>${f.name}</strong><small>${f.description}</small><span class="card-action">Abrir visor 3D →</span>`;q.onclick=()=>location.href=`?cliente=${slug}&mueble=${m}`;document.getElementById('furnitureList').append(q)}};document.getElementById('clientList').append(b)} document.getElementById('backToClients').onclick=()=>location.href=location.pathname}
if(!direct){catalogView();}else start();
function start(){document.getElementById('catalogApp').hidden=true;document.getElementById('viewerApp').hidden=false;document.getElementById('clientName').textContent='PICKY KIDS · GUÍA DE ARMADO 3D';document.getElementById('productName').textContent='Librero Emi';document.getElementById('sceneName').textContent='Librero';document.getElementById('homeButton').onclick=()=>location.href=location.pathname;const select=document.getElementById('pieceSelect');select.innerHTML='<option value="lateral">Laterales</option><option value="separador">Separador con manija</option><option value="base">Base</option><option value="frente">Frentes</option>';
const canvas=document.getElementById('viewer'), renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.outputColorSpace=THREE.SRGBColorSpace;const scene=new THREE.Scene();scene.background=new THREE.Color(0xe9eee9);const camera=new THREE.PerspectiveCamera(32,1,.1,30),controls=new OrbitControls(camera,canvas);camera.position.set(7,5.5,8);controls.target.set(0,2,0);controls.enableDamping=true;scene.add(new THREE.HemisphereLight(0xffffff,0x66736c,2.5));const light=new THREE.DirectionalLight(0xffffff,3);light.position.set(5,8,6);light.castShadow=true;scene.add(light);
const wood=new THREE.MeshStandardMaterial({color:0xd7a16e,roughness:.65}), red=new THREE.MeshStandardMaterial({color:0xe3262e,roughness:.45,emissive:0x580000,emissiveIntensity:.18}), dot=new THREE.MeshStandardMaterial({color:0x26322e,roughness:.3,metalness:.35});const root=new THREE.Group();root.scale.setScalar(.01);scene.add(root);const groups={},meshes=[];function part(name,geo,pos,ex){const g=new THREE.Group();g.position.set(...pos);g.userData={base:new THREE.Vector3(...pos),ex:new THREE.Vector3(...ex),name};const m=new THREE.Mesh(geo,wood);m.castShadow=m.receiveShadow=true;m.userData={name,g};g.add(m,new THREE.LineSegments(new THREE.EdgesGeometry(geo),new THREE.LineBasicMaterial({color:0x70452b,transparent:true,opacity:.45})));root.add(g);(groups[name]??=[]).push(g);meshes.push(m);return g}function box(name,a,b,c,pos,ex){return part(name,new THREE.BoxGeometry(a,b,c),pos,ex)}function points(g,arr,axis='z'){for(const [x,y,z] of arr){const h=new THREE.Mesh(new THREE.CylinderGeometry(3,3,1.3,20),dot);h.position.set(x,y,z);if(axis==='z')h.rotation.x=Math.PI/2;g.add(h)}}
const T=18.5,W=503.9,D=305,H=389;function sideGeo(mirror){const s=new THREE.Shape();
// Contorno muestreado de la polilínea DXF 27E (305 x 390 mm). Mantiene los
// rebajes superiores y la conicidad inferior del lateral real.
const p=[[.50,.91],[.23,.923],[.204,.971],[.17,.998],[.035,.997],[.003,.970],[.001,.633],[.026,.602],[.152,.595],[.196,.578],[.344,.083],[.396,.028],[.470,.002],[.542,.004],[.619,.038],[.662,.098],[.812,.584],[.885,.595],[.983,.607],[1,.638],[.993,.978],[.955,.999],[.820,.994],[.794,.966],[.764,.917]];
p.forEach(([z,y],i)=>{const zz=z*D,yy=y*H;i?s.lineTo(zz,yy):s.moveTo(zz,yy)});s.closePath();const g=new THREE.ExtrudeGeometry(s,{depth:T,bevelEnabled:true,bevelSize:2,bevelThickness:2,bevelSegments:2});g.rotateY(Math.PI/2);g.translate(mirror?-T/2:T/2,-H/2,-D/2);return g}
const l=part('lateral',sideGeo(false),[-W/2+T/2,H/2,0],[-90,0,0]),r=part('lateral',sideGeo(true),[W/2-T/2,H/2,0],[90,0,0]);points(l,[[-5,40,-110],[-5,135,-110],[-5,230,-110],[-5,315,-50]]);points(r,[[5,40,-110],[5,135,-110],[5,230,-110],[5,315,-50]]);
const base=box('base',W,T,269,[0,35,0],[0,-80,0]);points(base,[[-188,0,-112],[188,0,-112],[0,0,-112]]);
// El separador es una repisa horizontal de 503.9 x 370 mm; el rebaje de
// manija queda hacia el frente y se representa con la manija de referencia.
const sep=box('separador',W,T,370,[0,220,0],[0,0,100]);points(sep,[[-220,0,-155],[220,0,-155],[-220,0,155],[220,0,155]],'z');const handle=new THREE.Mesh(new THREE.TorusGeometry(42,8,12,32,Math.PI),new THREE.MeshStandardMaterial({color:0xf6f1e9,roughness:.8}));handle.rotation.x=Math.PI;handle.position.set(0,220,-180);sep.add(handle);
for(const y of [90,196]){const f=box('frente',W,106,T,[0,y,-145],[0,0,-100]);points(f,[[-188,0,10],[0,0,10],[188,0,10]],'z')}
const floor=new THREE.Mesh(new THREE.CircleGeometry(8,64),new THREE.MeshStandardMaterial({color:0xd7ddd6,roughness:1}));floor.rotation.x=-Math.PI/2;floor.receiveShadow=true;scene.add(floor);let current=route.get('pieza')||'lateral',amount=0;function set(){meshes.forEach(m=>m.material=m.userData.name===current?red:wood);select.value=current}function explode(v){amount=v;Object.values(groups).flat().forEach(g=>g.position.copy(g.userData.base).addScaledVector(g.userData.ex,v))}select.onchange=e=>{current=e.target.value;set();const u=new URL(location.href);u.searchParams.set('pieza',current);history.replaceState({},'',u)};document.getElementById('explode').oninput=e=>explode(e.target.value/100);document.getElementById('explodeButton').onclick=()=>{const n=amount>.5?0:1;document.getElementById('explode').value=n*100;explode(n);document.getElementById('explodeButton').textContent=n?'Volver a ver armado':'Ver despiece completo'};const ray=new THREE.Raycaster(),mouse=new THREE.Vector2();canvas.onclick=e=>{const q=canvas.getBoundingClientRect();mouse.set((e.clientX-q.left)/q.width*2-1,-(e.clientY-q.top)/q.height*2+1);ray.setFromCamera(mouse,camera);const hit=ray.intersectObjects(meshes)[0];if(hit){current=hit.object.userData.name;set();select.value=current}};function loop(){const w=canvas.clientWidth,h=canvas.clientHeight;if(canvas.width!==w*renderer.getPixelRatio()){renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}controls.update();renderer.render(scene,camera);requestAnimationFrame(loop)}set();loop();document.getElementById('loading').classList.add('ready')}
