import * as THREE from 'three';
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js';
import { catalog, defaultClient, defaultFurniture, getProduct } from './catalog.js';
import './styles.css';

const route=new URLSearchParams(location.search), product=getProduct(route.get('cliente')||defaultClient,route.get('mueble')||defaultFurniture), direct=route.has('mueble')||route.has('pieza')||route.has('p');
function catalogView(){document.getElementById('clientList').innerHTML='';document.getElementById('furnitureList').innerHTML='';for(const [slug,c] of Object.entries(catalog)){const b=document.createElement('button');b.className='catalog-card';b.innerHTML=`<span class="card-label">CLIENTE</span><strong>${c.name}</strong><small>${c.client} · ${c.description}</small><span class="card-action">Ver muebles →</span>`;b.onclick=()=>{document.getElementById('clientStep').hidden=true;document.getElementById('furnitureStep').hidden=false;document.getElementById('selectedClientName').textContent=`${c.name} · ${c.client}`;for(const [m,f] of Object.entries(c.furniture)){const q=document.createElement('button');q.className='catalog-card';q.innerHTML=`<span class="card-label">MUEBLE</span><strong>${f.name}</strong><small>${f.description}</small><span class="card-action">Abrir visor 3D →</span>`;q.onclick=()=>location.href=`?cliente=${slug}&mueble=${m}`;document.getElementById('furnitureList').append(q)}};document.getElementById('clientList').append(b)}document.getElementById('backToClients').onclick=()=>location.href=location.pathname}
if(!direct)catalogView();else start();
function start(){
 document.getElementById('catalogApp').hidden=true;document.getElementById('viewerApp').hidden=false;document.getElementById('clientName').textContent='PICKY KIDS · GUÍA DE ARMADO 3D';document.getElementById('productName').textContent='Librero Emi';document.getElementById('sceneName').textContent='Librero';document.getElementById('homeButton').onclick=()=>location.href=location.pathname;
 const select=document.getElementById('pieceSelect');select.innerHTML='<option value="lateral">Laterales</option><option value="separador">Separador con manija</option><option value="base">Base</option><option value="frente">Frentes</option>';
 const canvas=document.getElementById('viewer'),renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.outputColorSpace=THREE.SRGBColorSpace;const scene=new THREE.Scene();scene.background=new THREE.Color(0xe9eee9);const camera=new THREE.PerspectiveCamera(32,1,.1,30),controls=new OrbitControls(camera,canvas);camera.position.set(7.2,5.3,8.6);controls.target.set(0,2.1,0);controls.enableDamping=true;scene.add(new THREE.HemisphereLight(0xffffff,0x66736c,2.4));const light=new THREE.DirectionalLight(0xffffff,3);light.position.set(5,8,6);light.castShadow=true;scene.add(light);
 const wood=new THREE.MeshStandardMaterial({color:0xd7a16e,roughness:.65}),red=new THREE.MeshStandardMaterial({color:0xe3262e,roughness:.45,emissive:0x580000,emissiveIntensity:.18}),dotMat=new THREE.MeshStandardMaterial({color:0x1f55d6,roughness:.3,metalness:.35});const root=new THREE.Group();root.scale.setScalar(.01);scene.add(root);const groups={},meshes=[],dots=[];
 function part(name,geo,pos,ex){const g=new THREE.Group();g.position.set(...pos);g.userData={base:new THREE.Vector3(...pos),ex:new THREE.Vector3(...ex),name};const m=new THREE.Mesh(geo,wood);m.castShadow=m.receiveShadow=true;m.userData={name,g};g.add(m,new THREE.LineSegments(new THREE.EdgesGeometry(geo),new THREE.LineBasicMaterial({color:0x70452b,transparent:true,opacity:.45})));root.add(g);(groups[name]??=[]).push(g);meshes.push(m);return g}
 function box(name,a,b,c,pos,ex){return part(name,new THREE.BoxGeometry(a,b,c),pos,ex)}
 function hole(g,x,y,z,axis='x'){const h=new THREE.Mesh(new THREE.CylinderGeometry(4,4,2.4,16),dotMat);h.position.set(x,y,z);if(axis==='z')h.rotation.x=Math.PI/2;if(axis==='y')h.rotation.z=Math.PI/2;h.visible=false;g.add(h);dots.push(h)}
 function lateralGeo(){const s=new THREE.Shape(),p=[[.50,.91],[.23,.923],[.204,.971],[.17,.998],[.035,.997],[.003,.970],[.001,.633],[.026,.602],[.152,.595],[.196,.578],[.344,.083],[.396,.028],[.470,.002],[.542,.004],[.619,.038],[.662,.098],[.812,.584],[.885,.595],[.983,.607],[1,.638],[.993,.978],[.955,.999],[.820,.994],[.794,.966],[.764,.917]];p.forEach(([z,y],i)=>{const zz=z*305,yy=y*389;i?s.lineTo(zz,yy):s.moveTo(zz,yy)});s.closePath();const g=new THREE.ExtrudeGeometry(s,{depth:18.5,bevelEnabled:true,bevelSize:2,bevelThickness:2,bevelSegments:2});g.rotateY(Math.PI/2);g.translate(-9.25,-194.5,-152.5);return g}
 function shelfGeo(depth){const s=new THREE.Shape(),w=503.9,n=52;[[-w/2,-depth/2],[-n,-depth/2],[-n+16,-depth/2+22],[n-16,-depth/2+22],[n,-depth/2],[w/2,-depth/2],[w/2,depth/2],[-w/2,depth/2]].forEach(([x,z],i)=>i?s.lineTo(x,z):s.moveTo(x,z));s.closePath();const g=new THREE.ExtrudeGeometry(s,{depth:18.5,bevelEnabled:true,bevelSize:1.5,bevelThickness:1.5,bevelSegments:2});g.rotateX(-Math.PI/2);g.translate(0,-9.25,0);return g}
 const T=18.5,W=503.9,H=389,D=305,left=part('lateral',lateralGeo(),[-W/2+T/2,H/2,0],[-100,0,0]),right=part('lateral',lateralGeo(),[W/2-T/2,H/2,0],[100,0,0]);
 [[.50,.07],[.50,.76],[0,.77],[.18,1],[.82,1],[1,.77],[.50,.41],[0,.94],[1,.94],[.50,.06],[.50,.94]].forEach(([x,y])=>hole(left,-9.25,y*H-H/2,x*D-D/2));[[.39,0],[.39,.23],[.50,.58],[.50,.94],[1,.99],[1,.60],[.50,.24],[.50,0],[.50,.99]].forEach(([x,y])=>hole(right,9.25,y*H-H/2,x*D-D/2));
 const base=part('base',shelfGeo(269),[0,35,0],[0,-65,0]);[[-188,-112],[0,-112],[188,-112],[-188,112],[0,112],[188,112],[0,0]].forEach(([x,z])=>hole(base,x,0,z,'y'));
 const sep=part('separador',shelfGeo(370),[0,220,0],[0,35,0]);[[-220,-165],[220,-165],[-220,165],[220,165],[0,-165],[0,165]].forEach(([x,z])=>hole(sep,x,0,z,'y'));
 const f1=box('frente',W,106,T,[0,90,-145],[0,0,-90]),f2=box('frente',W,106,T,[0,196,-145],[0,0,-90]);for(const f of [f1,f2])[-188,0,188].forEach(x=>hole(f,x,0,-2,'y'));
 const floor=new THREE.Mesh(new THREE.CircleGeometry(8,64),new THREE.MeshStandardMaterial({color:0xd7ddd6,roughness:1}));floor.rotation.x=-Math.PI/2;floor.receiveShadow=true;scene.add(floor);let current=route.get('pieza')||'lateral',amount=0;
 function refresh(){meshes.forEach(m=>m.material=m.userData.name===current?red:wood);dots.forEach(d=>d.visible=amount>.03);select.value=current}function explode(v){amount=v;Object.values(groups).flat().forEach(g=>g.position.copy(g.userData.base).addScaledVector(g.userData.ex,v));dots.forEach(d=>d.visible=v>.03)}select.onchange=e=>{current=e.target.value;refresh();const u=new URL(location.href);u.searchParams.set('pieza',current);history.replaceState({},'',u)};document.getElementById('explode').oninput=e=>explode(e.target.value/100);document.getElementById('explodeButton').onclick=()=>{const n=amount>.5?0:1;document.getElementById('explode').value=n*100;explode(n);document.getElementById('explodeButton').textContent=n?'Volver a ver armado':'Ver despiece completo'};const ray=new THREE.Raycaster(),mouse=new THREE.Vector2();canvas.onclick=e=>{const q=canvas.getBoundingClientRect();mouse.set((e.clientX-q.left)/q.width*2-1,-(e.clientY-q.top)/q.height*2+1);ray.setFromCamera(mouse,camera);const hit=ray.intersectObjects(meshes)[0];if(hit){current=hit.object.userData.name;refresh()}};function loop(){const w=canvas.clientWidth,h=canvas.clientHeight;if(canvas.width!==w*renderer.getPixelRatio()){renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}controls.update();renderer.render(scene,camera);requestAnimationFrame(loop)}refresh();loop();document.getElementById('loading').classList.add('ready')}
